### ISSUE TITLE
Excuse me, can the training dataset and training model be downloaded? Thank you！

### ISSUE THREAD

**Issue by QQ2737499951** [znxlwm/UGATIT-pytorch#13]
Excuse me, can the training dataset and training model be downloaded? Thank you！

**Comment by taki0112** [comment]
1. We released [**50 epoch**](https://drive.google.com/file/d/1V6GbSItG3HZKv3quYs7AP0rr1kOCT3QO/view) and [**100 epoch**](https://drive.google.com/file/d/19xQK2onIy-3S5W5K-XIh85pAg_RNvBVf/view) checkpoints so that people could test more widely.

2. Also, We published [**the selfie2anime datasets**](https://drive.google.com/file/d/1xOWj1UVgp6NKMT3HbPhBbtq2A4EDkghF/view) we used in the paper.

3. In the test image, I recommend that the face be in the **center**.
